### ISSUE TITLE
ExampleServer on the readme not compiling

### ISSUE THREAD

**Issue by mfirry** [polynote/uzhttp#9]
Hi, I'm trying to use uzhttp so obviously I was trying the example on the readme file but I can't compile it.

Error is

```
[error] /Users/yolo/uzhttp/src/main/scala/q/Main.scala:13:15: type mismatch;
[error]  found   : zio.ZIO[Any with zio.blocking.Blocking with zio.clock.Clock,Throwable,Nothing]
[error]     (which expands to)  zio.ZIO[Any with zio.Has[zio.blocking.Blocking.Service] with zio.Has[zio.clock.Clock.Service],Throwable,Nothing]
[error]  required: zio.ZIO[zio.ZEnv,Nothing,Int]
[error]     (which expands to)  zio.ZIO[zio.Has[zio.clock.Clock.Service] with zio.Has[zio.console.Console.Service] with zio.Has[zio.system.System.Service] with zio.Has[zio.random.Random.Service] with zio.Has[zio.blocking.Blocking.Service],Nothing,Int]
[error]       }.serve.useForever
```

**Comment by mfirry** [comment]
Ok for the `html` case I managed to make it work just by wrapping it into `ZIO.succeed(...)`

**Comment by mfirry** [comment]
Ok, looks like it works if one would `mapError` on the `Response.fromResource(...)`

**Comment by jeremyrsmith** [comment]
Ah, this is because most of the `Response.fromX` constructors can fail with `Throwable` (because they call Java stuff) but your request handler has to only return `HTTPError`. The fact that you have to handle those `Throwable` isn't reflected in the README.

Maybe we should add a convenience thing that gives you an easy default way to map `Throwable` into `HTTPError` (e.g. turn `FileNotFoundException` into 404, everything else into 500. Something like that)

**Comment by mfirry** [comment]
I guess. The `Throwable` comes from `effectBlocking` or similar right?

**Comment by jeremyrsmith** [comment]
Yes, it's the default error type... we can't unilaterally refine it when there are filesystem calls and such involved. But we could provide a sensible default for when you don't want to deal with it.

**Comment by mfirry** [comment]
Right. The `ZIO.succeed` part should be added though right?
